version: '3'
services:
  config-server:
    image: config-server:latest
    build:
      context: ./spring-core/config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/config-server/mysql-development" ]
      interval: 30s
      timeout: 10s
      retries: 5
  e-shop:
    image: e-shop:latest
    build:
      context: ./tutorial/e-shop/demo
      dockerfile: Dockerfile
    depends_on:
      config-server:
        condition: service_healthy
    ports:
      - 9091:9091