version: '2.2'
services:
  configuration-server:
    build:
      context: ./configuration-server
      dockerfile: Dockerfile
    image: configuration-server
    ports:
      - 8888:8888
    networks:
      - pinenetwork
  activemq-sample:
    build:
      context: ./sample/activemq-sample/
      dockerfile: Dockerfile
    image: activemq-sample
    ports:
      - 9091:9091
    networks:
      - pinenetwork

networks:
  pinenetwork:
