version: '2.2'
services:
  config-server:
    image: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - 8888:8888
    networks:
      - pineframework
  activemq-sample:
    image: activemq-sample
    build:
      context: ./tutorial/activemq-sample/rest-api
      dockerfile: Dockerfile
    depends_on:
      - config-server
    ports:
      - 9091:9091
    networks:
      - pineframework
networks:
  pineframework:
