version: '3'
services:
  pine-mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Root1234
      MYSQL_DATABASE: pine
    ports:
      - 3306
    healthcheck:
      test: "mysqladmin --host=127.0.0.1 --user=root --password=Root1234 status"
      interval: 1s
      retries: 120
  pine-discovery-server-eureka:
    hostname: "pine-discovery-server-eureka"
    image: discovery-server-eureka:latest
    build:
      context: ./core-spring/discovery-server-eureka
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  pine-config-server:
    hostname: "pine-config-server"
    image: config-server:latest
    build:
      context: ./core-spring/config-server
      dockerfile: Dockerfile
    depends_on:
      pine-discovery-server-eureka:
        condition: service_healthy
    links:
      - pine-discovery-server-eureka
    ports:
      - 8888:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
  pine-eshop:
    hostname: "pine-e-shop"
    image: eshop:latest
    build:
      context: ./tutorial/eshop/rest-api
      dockerfile: Dockerfile
    depends_on:
      pine-discovery-server-eureka:
        condition: service_healthy
      pine-config-server:
        condition: service_healthy
      pine-mysql:
        condition: service_healthy
    links:
      - pine-discovery-server-eureka
      - pine-config-server
      - pine-mysql
    ports:
      - 9091:9091
  pine-test:
    image: openjdk:8
    command: tail -F anything