apiVersion: v1
kind: Service
metadata:
  name: pine-eshop
  labels:
    name: pine-eshop
spec:
  type: NodePort
  selector:
    app: pine-eshop
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pine-eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pine-eshop
  template:
    metadata:
      labels:
        app: pine-eshop
    spec:
      containers:
        - name: pine-eshop
          image: samanalishiri/eshop:1.0.0-SNAPSHOT
          ports:
            - containerPort: 9091