apiVersion: v1
kind: Service
metadata:
  name: pine-mysql
  labels:
    app: pine-mysql
    tier: database
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: pine-mysql
    tier: database
  clusterIP: None
---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: pine-mysql-pv
#  labels:
#    type: local
#spec:
#  storageClassName: standard
#  capacity:
#    storage: 250Mi
#  accessModes:
#    - ReadWriteOnce
#  hostPath:
#    path: "/mnt/data"
#  persistentVolumeReclaimPolicy: Retain
#---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pine-mysql-pvc
  labels:
    app: pine-mysql
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pine-mysql
  labels:
    app: pine-mysql
    tier: database
spec:
  selector:
    matchLabels:
      app: pine-mysql
      tier: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pine-mysql
        tier: database
    spec:
      containers:
        - image: mysql:8.0
          name: pine-mysql
          imagePullPolicy: "IfNotPresent"
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mysql-configmap
                  key: database
            - name: MYSQL_USER
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: username
            - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secret
                    key: password
          ports:
            - containerPort: 3306
              name: pine-mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pine-mysql-pvc