@startuml
skinparam shadowing false
rectangle "Core Component" as coreComponent {

    together {
        component "I18N" as i18n
        component "Document" as document
    }

    together {
        component "Data Model" as dataModel
        component "Helper" as helper
        component "Test" as test
        component "Contract" as contract
        component "Business" as business
    }

    contract ..> dataModel
    contract ..> helper
    business ..> contract
    test .right.> contract
}
@enduml