server:
  address: ${CONFIG_SERVER_HOST:0.0.0.0}
  port: ${CONFIG_SERVER_PORT:8888}
spring:
  main:
    banner-mode: off
  profiles:
    active: ${PROFILES:development}
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          uri: ${CONFIG_REPOSITORY_URL}
          search-paths: ${CONFIG_REPOSITORY}