server:
  address: ${CONFIG_SERVER_HOST:0.0.0.0}
  port: ${CONFIG_SERVER_PORT:8888}
  ssl:
    enabled: true
    key-store: classpath:client.jks
    key-store-password: 123456
    key-password: 123456
    trust-store: classpath:client.jks
    trust-store-password: 123456
    key-alias: client
    client-auth: want
    key-store-type: JKS
    trust-store-type: JKS
spring:
  main:
    banner-mode: off
  profiles:
    active: ${PROFILES}
  cloud:
    config:
      server:
        git:
          cloneOnStart: true
          uri: ${CONFIG_REPOSITORY_URL}
          search-paths: ${CONFIG_REPOSITORY}