@startuml
skinparam shadowing false
rectangle "Domain" as domain{

rectangle "Base Component" as baseComponent {
component "Data Model" as dataModel
component "Helper" as helper
component "Test" as test
component "I18N" as i18n
component "Contract" as contract
component "Dependencies" as dependencies
component "Business" as business
helper ..> test
contract ..> dataModel
contract ..> helper
dependencies ..> contract
dependencies ..> i18n
business ..> dependencies
business ..> test
}

rectangle "Facility Component" as facilityComponent {
component "Initializer Dependencies" as initDependencies
component "Classic Queue" as classicQueue
classicQueue ..> dependencies
initDependencies ..> i18n
initDependencies -[hidden]up- classicQueue
}

rectangle "Domain Component Template" as templateComponent{
component "component" as comp
component "Business Service" as businessService
component "Model" as model
component "Exposer" as exposer
comp ..> dependencies
comp ..> test
comp *- businessService
comp *- model
comp *- exposer
businessService ..> model
exposer ..> businessService
}


}

@enduml