@startuml
skinparam shadowing false
rectangle "Core Component" as coreComponent {

    together {
        component "I18N" as i18n
        component "Document" as coreDocument
    }

    together {
        component "Data Model" as dataModel
        component "Helper" as helper
        component "Test" as coreTest
        component "Contract" as contract
        component "Business" as coreBusiness
    }

    contract ..> dataModel
    contract ..> helper
    coreBusiness ..> contract
    coreTest .right.> contract
}
@enduml