apiVersion: v1
kind: Service
metadata:
  name: pine-eshop
  labels:
    name: pine-eshop
spec:
  type: NodePort
  selector:
    app: pine-eshop
  ports:
    - nodePort: 30001
      protocol: TCP
      port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pine-eshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pine-eshop
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: pine-eshop
    spec:
      containers:
        - name: pine-eshop
          image: samanalishiri/eshop:1.0.0-SNAPSHOT
          ports:
            - containerPort: 9091
          imagePullPolicy: Always
          env:
            - name: ESHOP_HOST
              value: "0.0.0.0"
            - name: ESHOP_PORT
              value: "9091"
            - name: HOSTNAME
              value: "pine-eshop"
            - name: ENVIRONMENT
              value: "Development"
            - name: PROFILES
              value: "development,eureka-server,config-server,i18n,mysql,hibernate,messaging,activemq,US"
            - name: MYSQL_HOST
              value: "pine-mysql:3306"
            - name: MYSQL_DATABASE
              value: "eshop"
            - name: MYSQL_PASSWORD
              value: "pine"
            - name: MYSQL_USERNAME
              value: "pine"
            - name: HIBERNATE_DIALECT
              value: "org.hibernate.dialect.MySQL8Dialect"
            - name: DATABASE_SCHEMA
              value: "ESHOP"
            - name: ACTIVEMQ_URL
              value: "tcp://pine-activemq:61616"
            - name: ACTIVEMQ_USER
              value: "admin"
            - name: ACTIVEMQ_PASSWORD
              value: "admin"
            - name: ACTIVEMQ_QUEUES
              value: "eshop,status"
            - name: EUREKA_SERVER_URL
              value: "http://pine-eureka-server:8761/eureka"
            - name: CONFIG_SERVER_URL
              value: "http://pine-config-server:8888"
      initContainers:
        - name: init-pine-mysql
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup pine-mysql; do echo waiting for pine-mysql; sleep 2; done;' ]
        - name: init-pine-activemq
          image: busybox:1.28
          command: [ 'sh', '-c', 'until nslookup pine-activemq; do echo waiting for pine-activemq; sleep 2; done;' ]